trigger:
  branches:
    include:
      - main

pool:
  
  name: Default
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhubservice'
      repository: 'ayoubaitbarka/backendboutique'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        latest
